//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearthstone_Collection_Tracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hearthstone_Collection_Tracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractured in Alterac Valley.
        /// </summary>
        internal static string CARDSET_ALTERAC_VALLEY {
            get {
                return ResourceManager.GetString("CARDSET_ALTERAC_VALLEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival of Legends.
        /// </summary>
        internal static string CARDSET_BATTLE_OF_THE_BANDS {
            get {
                return ResourceManager.GetString("CARDSET_BATTLE_OF_THE_BANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashes of Outland.
        /// </summary>
        internal static string CARDSET_BLACK_TEMPLE {
            get {
                return ResourceManager.GetString("CARDSET_BLACK_TEMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Boomsday Project.
        /// </summary>
        internal static string CARDSET_BOOMSDAY {
            get {
                return ResourceManager.GetString("CARDSET_BOOMSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackrock Mountain.
        /// </summary>
        internal static string CARDSET_BRM {
            get {
                return ResourceManager.GetString("CARDSET_BRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise of Shadows.
        /// </summary>
        internal static string CARDSET_DALARAN {
            get {
                return ResourceManager.GetString("CARDSET_DALARAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madness at the Darkmoon Faire.
        /// </summary>
        internal static string CARDSET_DARKMOON_FAIRE {
            get {
                return ResourceManager.GetString("CARDSET_DARKMOON_FAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demon Hunter Initiate.
        /// </summary>
        internal static string CARDSET_DEMON_HUNTER_INITIATE {
            get {
                return ResourceManager.GetString("CARDSET_DEMON_HUNTER_INITIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent of Dragons.
        /// </summary>
        internal static string CARDSET_DRAGONS {
            get {
                return ResourceManager.GetString("CARDSET_DRAGONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy.
        /// </summary>
        internal static string CARDSET_EXPERT1 {
            get {
                return ResourceManager.GetString("CARDSET_EXPERT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Streets of Gadgetzan.
        /// </summary>
        internal static string CARDSET_GANGS {
            get {
                return ResourceManager.GetString("CARDSET_GANGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Witchwood.
        /// </summary>
        internal static string CARDSET_GILNEAS {
            get {
                return ResourceManager.GetString("CARDSET_GILNEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goblins vs Gnomes.
        /// </summary>
        internal static string CARDSET_GVG {
            get {
                return ResourceManager.GetString("CARDSET_GVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Fame.
        /// </summary>
        internal static string CARDSET_HOF {
            get {
                return ResourceManager.GetString("CARDSET_HOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knights of the Frozen Throne.
        /// </summary>
        internal static string CARDSET_ICECROWN {
            get {
                return ResourceManager.GetString("CARDSET_ICECROWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Night in Karazhan.
        /// </summary>
        internal static string CARDSET_KARA {
            get {
                return ResourceManager.GetString("CARDSET_KARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League of Explorers.
        /// </summary>
        internal static string CARDSET_LOE {
            get {
                return ResourceManager.GetString("CARDSET_LOE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kobolds and Catacombs.
        /// </summary>
        internal static string CARDSET_LOOTAPALOOZA {
            get {
                return ResourceManager.GetString("CARDSET_LOOTAPALOOZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curse of Naxxramas.
        /// </summary>
        internal static string CARDSET_NAXX {
            get {
                return ResourceManager.GetString("CARDSET_NAXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whispers of the Old Gods.
        /// </summary>
        internal static string CARDSET_OG {
            get {
                return ResourceManager.GetString("CARDSET_OG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goblins vs Gnomes.
        /// </summary>
        internal static string CARDSET_PE1 {
            get {
                return ResourceManager.GetString("CARDSET_PE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Grand Tournament.
        /// </summary>
        internal static string CARDSET_PE2 {
            get {
                return ResourceManager.GetString("CARDSET_PE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March of the Lich King.
        /// </summary>
        internal static string CARDSET_RETURN_OF_THE_LICH_KING {
            get {
                return ResourceManager.GetString("CARDSET_RETURN_OF_THE_LICH_KING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murder at Castle Nathria.
        /// </summary>
        internal static string CARDSET_REVENDRETH {
            get {
                return ResourceManager.GetString("CARDSET_REVENDRETH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Fame.
        /// </summary>
        internal static string CARDSET_REWARD {
            get {
                return ResourceManager.GetString("CARDSET_REWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholomance Academy.
        /// </summary>
        internal static string CARDSET_SCHOLOMANCE {
            get {
                return ResourceManager.GetString("CARDSET_SCHOLOMANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United in Stormwind.
        /// </summary>
        internal static string CARDSET_STORMWIND {
            get {
                return ResourceManager.GetString("CARDSET_STORMWIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Grand Tournament.
        /// </summary>
        internal static string CARDSET_TGT {
            get {
                return ResourceManager.GetString("CARDSET_TGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forged in the Barrens.
        /// </summary>
        internal static string CARDSET_THE_BARRENS {
            get {
                return ResourceManager.GetString("CARDSET_THE_BARRENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voyage to the Sunken City.
        /// </summary>
        internal static string CARDSET_THE_SUNKEN_CITY {
            get {
                return ResourceManager.GetString("CARDSET_THE_SUNKEN_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rastakhan&apos;s Rumble.
        /// </summary>
        internal static string CARDSET_TROLL {
            get {
                return ResourceManager.GetString("CARDSET_TROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saviors of Uldum.
        /// </summary>
        internal static string CARDSET_ULDUM {
            get {
                return ResourceManager.GetString("CARDSET_ULDUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey to Un&apos;Goro.
        /// </summary>
        internal static string CARDSET_UNGORO {
            get {
                return ResourceManager.GetString("CARDSET_UNGORO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string CARDSET_VANILLA {
            get {
                return ResourceManager.GetString("CARDSET_VANILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galakrond&apos;s Awakening.
        /// </summary>
        internal static string YEAR_OF_THE_DRAGON {
            get {
                return ResourceManager.GetString("YEAR_OF_THE_DRAGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of the Dragon.
        /// </summary>
        internal static string ZODIACYEAR_DRAGON {
            get {
                return ResourceManager.GetString("ZODIACYEAR_DRAGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of the Gryphon.
        /// </summary>
        internal static string ZODIACYEAR_GRYPHON {
            get {
                return ResourceManager.GetString("ZODIACYEAR_GRYPHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of the Hydra.
        /// </summary>
        internal static string ZODIACYEAR_HYDRA {
            get {
                return ResourceManager.GetString("ZODIACYEAR_HYDRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ZODIACYEAR_INVALID {
            get {
                return ResourceManager.GetString("ZODIACYEAR_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of the Kraken.
        /// </summary>
        internal static string ZODIACYEAR_KRAKEN {
            get {
                return ResourceManager.GetString("ZODIACYEAR_KRAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of the Mammoth.
        /// </summary>
        internal static string ZODIACYEAR_MAMMOTH {
            get {
                return ResourceManager.GetString("ZODIACYEAR_MAMMOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of the Phoenix.
        /// </summary>
        internal static string ZODIACYEAR_PHOENIX {
            get {
                return ResourceManager.GetString("ZODIACYEAR_PHOENIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years 1 &amp; 2.
        /// </summary>
        internal static string ZODIACYEAR_PRE_STANDARD {
            get {
                return ResourceManager.GetString("ZODIACYEAR_PRE_STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of the Raven.
        /// </summary>
        internal static string ZODIACYEAR_RAVEN {
            get {
                return ResourceManager.GetString("ZODIACYEAR_RAVEN", resourceCulture);
            }
        }
    }
}
